controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

adminComment:
    path: /commentAdmin/{name}
    controller: 'App\Controller\admin\AdminCommentController::base'

adminCategory:
    path: /categoryAdmin/{category}
    controller: 'App\Controller\admin\AdminCommentController::base'

default_target_path:
    path: /
    controller: 'App\Controller\CategoryController::AllCategory'